#!/bin/bash -l
#PBS -l nodes=1:ppn=8
#PBS -l walltime=6:00:00
#PBS -r n
#PBS -j oe
#PBS -q workq

# NOTE: for hpq and sandyq, ppn<=16
#       for greenq ppn<=32
#       multiples of 8 are preferred for ppn, e.g., ppn=8,16, or 32
# If you are using nodes=1 and ppn<=8, please use the workq instead

# go to your working directory
cd /home/gamvrelis/PLUTO/Work/9_mag_dipole_current

# Load your modules
# If you use module purge, make sure to load the maui and torque modules
# e.g.,
# module purge
# module load maui torque

# Intel compiler and MPI
module load intel intelmpi

# or for OpenMPI
# module load gcc/7.3.0 openmpi/3.0.0-gcc-7.3.0

#mpirun ./your_mpi_code your_arguments

# NOTE: mpirun without args will use all available cores e.g, 8x16=128 in this example
# To limit the number of cores per host (say for hybrid Openmp/OpenMPI codes) use one of the
# mpirun load balancing options
# e.g., for OpenMPI one

mpirun -np 8 -map-by node:SPAN ./pluto
